---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-subpath
spec:
  containers:
  - image: nginx
    name: nginx-subpath
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/subpath
      subPath: a/b
  volumes:
  - name: test-volume
    hostPath:
      path: /mnt/

