---
apiVersion: v1
kind: Pod
metadata:
  name: aspnet-gitrepo
spec:
  containers:
  - image: microsoft/aspnet:4.7.1-windowsservercore-1709
    name: aspnet-gitrepo
    volumeMounts:
    - mountPath: /mnt/gitrepo
      name: git-volume
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
  - name: git-volume
    gitRepo:
      repository: "https://github.com/andyzhangx/Demo.git"
