kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hdd
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS  #available values: Standard_LRS, Premium_LRS, and StandardSSD_LRS, UltraSSD_LRS are supported from k8s v1.13.0
  kind: managed
  cachingmode: None
