apiVersion: v1
kind: Pod
metadata:
  name: aspnet-flex-example
spec:
  containers:
  - name: aspnet-flex-example
    image: microsoft/aspnet
    volumeMounts:
    - name: flextest
      mountPath: /data
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
  - name: flextest
    flexVolume:
      driver: "test/example.cmd"
