apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blobfuse-flexvol-installer
  namespace: kube-system
  labels:
    k8s-app: blobfuse
spec:
  selector:
    matchLabels:
      name: blobfuse
  template:
    metadata:
      labels:
        name: blobfuse
    spec:
      containers:
      - name: blobfuse-flexvol-installer
        image: andyzhangx/blobfuse-flexvol-installer:1.0
        securityContext:
          privileged: true        
        volumeMounts:
        - name: volplugins
          mountPath: /etc/kubernetes/volumeplugins/
        - name: usrlib
          mountPath: /usr/lib/         
      volumes:
      - name: usrlib
        hostPath:
          path: /usr/lib/      
      - name: volplugins
        hostPath:
          path: /etc/kubernetes/volumeplugins/
          type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
