kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: aspnet
  name: deployment-azurefile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet  
  template:
    metadata:
      labels:
        app: aspnet
      name: deployment-azurefile
    spec:
      containers:
      - name: deployment-azurefile
        image: microsoft/aspnet:4.7.2-windowsservercore-1803	
        volumeMounts:
        - name: azurefile01
          mountPath: '/mnt/azure'
      volumes:
      - name: azurefile01
        persistentVolumeClaim:
          claimName: pvc-azurefile
