kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-local-raw
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-local-raw
  storageClassName: local-storage
