apiVersion: v1
kind: Pod
metadata:
 name: aspnet-azuredisk
spec:
 containers:
 - image: microsoft/aspnet:4.7.1-windowsservercore-1709
   name: aspnet-azuredisk   
   volumeMounts:
   - name: disk01
     mountPath: 'D:'
 nodeSelector:
  beta.kubernetes.io/os: windows	  	 
 volumes:
 - name: disk01
   azureDisk:
     diskName: test.vhd
     diskURI: https://YOURSTORAGEACCOUNT.blob.core.windows.net/vhds/test.vhd
