---
kind: Pod
apiVersion: v1
metadata:
  name: aspnet-azuredisk
  labels:
    name: storage
spec:
  containers:
  - image: microsoft/aspnet
    name: aspnet-azuredisk
    volumeMounts:
    - name: disk01
      mountPath: 'D:'
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
  - name: disk01
    persistentVolumeClaim:
      claimName: pvc-azuredisk

