---
kind: Pod
apiVersion: v1
metadata:
  name: aspnet
spec:
  containers:
  - image: microsoft/aspnet
    name: aspnet
    volumeMounts:
    - mountPath: 'D:'
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  nodeSelector:
    beta.kubernetes.io/os: windows

