apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-flobfuse
spec:
  containers:
  - name: nginx-flex-flobfuse
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "flobfuse/flobfuse"
      readOnly: true
      secretRef:
        name: blobfusecreds
      options:
        container: CONTAINER-NAME
